# Site settings
title: My Blog
email: kyle.wolff7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about my life.
baseurl: "/myblog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Kyle_Wolff
github_username:  kylewolff

# Build settings
markdown: redcarpet
